### ISSUE TITLE
App - Spielerlobby erstellen (Client Logik)

### ISSUE THREAD

**Issue by RNeumann12** [SE2-Gruppe-IV-DO2/FrontEnd#19]
Die Logik für denn Aufruf nach dem Click auf denn Button "Spiel erstellen" soll implementiert werden.
Dabei soll ein Aufruf auf die in #12 erstellte Logik erfolgen

**Comment by MaxAlex42** [comment]
Leider in Commit für #21 verpackt

**Comment by RNeumann12** [comment]
Anpassungen am Server fehlen noch (TextMessage statt String) -> mache ich schnell

**Comment by RNeumann12** [comment]
Passt
